// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bujnmwrufsflprnyyshe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1am5td3J1ZnNmbHBybnl5c2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTI4MzcsImV4cCI6MjA2MjYyODgzN30.FU8DrzMlC7RItz_5gsIW3MWmEhNfm0wG2EbyJBlVCAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);